[appConfigs]
    [appConfigs.development]
    AppName = "DulceDayServer"
    AuthTokenExpiresTime = 2592000000000000
    AuthTokenSecret = "qweasd123"
    AppAddress = "8080"
	DefaultDeviceName = "Known"

    [appConfigs.production]
    AppName = "DulceDayServer"
    AuthTokenExpiresTime = 2592000000000000
    AuthTokenSecret = "qweasd123"
    AppAddress = "7001"
	DefaultDeviceName = "Known"


[dataBaseConfigs]
    [dataBaseConfigs.development]
    Host = "localhost"
    Port = "3306"
    Collection = "DulceDay"
    User = "root"
    Password = "123456"
    QueryParameters = "charset=utf8mb4&parseTime=True&loc=Local"

    [dataBaseConfigs.production]
    Host = "localhost"
    Port = "7002"
    Collection = "DulceDay"
    User = "root"
    Password = "123456"
    QueryParameters = "charset=utf8mb4&parseTime=True&loc=Local"


[cacheConfigs]
    [cacheConfigs.development]
    Host = "localhost"
    Port = "6379"
    DB = 1
    BlackListName = "BlackList"
	RevokeTokenListName = "RevokeTokens"
	IPBlackListName = "IPBlackList"
	InActiveTokenListName = "InActiveTokens"

    [cacheConfigs.production]
    Host = "localhost"
    Port = "7003"
    DB = 1
    BlackListName = "BlackList"
	RevokeTokenListName = "RevokeTokens"
	IPBlackListName = "IPBlackList"
	InActiveTokenListName = "InActiveTokens"