# todo rabbitmq
# todo add godoc
version: '2.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'DulceDay'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    ports:
      - '7001:3306'
    volumes:
      - database:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  redis:
    image: redis:alpine
    ports:
      - '7002:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 10
volumes:
  database: