basePath: /v1
definitions:
  common.BaseResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  models.UserProfile:
    properties:
      nickname:
        type: string
      uid:
        type: string
      username:
        type: string
    type: object
  user.loginResponse:
    properties:
      code:
        type: integer
      message:
        type: string
      token:
        type: string
    type: object
  user.loginWithEmailParameter:
    properties:
      device_name:
        description: 登录的设备的名字，浏览器为 “浏览器(ip所在的城市)”
        example: bob的iPhone
        type: string
      email:
        description: 邮箱
        example: haha@test.com
        type: string
      password:
        description: 密码
        example: qwerty123
        type: string
    required:
    - email
    - password
    type: object
  user.loginWithUsernameParameter:
    properties:
      device_name:
        description: 登录的设备的名字，浏览器为 “浏览器(ip所在的城市)”
        example: bob的iPhone
        type: string
      password:
        description: 密码
        example: qwerty123
        type: string
      username:
        description: 用户名
        example: bob
        type: string
    required:
    - password
    - username
    type: object
  user.registerParameter:
    properties:
      email:
        description: 邮箱
        example: haha@test.com
        type: string
      password:
        description: 密码
        example: qwerty123
        type: string
      username:
        description: 用户名
        example: bob
        type: string
    required:
    - email
    - password
    - username
    type: object
  user.registerResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  user_profile.getProfileResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: 一个轻社区app, 内置直播, 帮助用户找到身边的兴趣圈
  license: {}
  termsOfService: http://swagger.io/terms/
  title: DulceDayServer
  version: "1.0"
paths:
  /user/login/email:
    post:
      parameters:
      - description: 参数
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.loginWithEmailParameter'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.loginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.BaseResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/common.BaseResponse'
      summary: 使用邮箱登陆
  /user/login/username:
    post:
      parameters:
      - description: 参数
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.loginWithUsernameParameter'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.loginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.BaseResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/common.BaseResponse'
      summary: 使用用户名登陆
  /user/profile:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user_profile.getProfileResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/common.BaseResponse'
      security:
      - ApiKeyAuth: []
      summary: 获取登录用户信息
  /user/profile/{username}:
    get:
      parameters:
      - description: 用户名
        in: path
        name: username
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user_profile.getProfileResponse'
      summary: 获取用户信息
  /user/register:
    post:
      parameters:
      - description: 参数
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/user.registerParameter'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.registerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.BaseResponse'
      summary: 注册
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
